version: "3.7"

services:
  web:
    image: satsale/satsale:0.0.1
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 8000:8000
    environment:
      # Bitcoin Core connection details
      BTCEXP_BITCOIND_HOST: $BITCOIN_IP
      BTCEXP_BITCOIND_PORT: $BITCOIN_RPC_PORT
      BTCEXP_BITCOIND_USER: $BITCOIN_RPC_USER
      BTCEXP_BITCOIND_PASS: $BITCOIN_RPC_PASS

